services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    # environment:
    #   RABBITMQ_DEFAULT_USER: rabbitmq
    #   RABBITMQ_DEFAULT_PASS: rabbitmqpw
    # volumes:
    #   - rabbitmqdata:/var/lib/rabbitmq/data
volumes:
  pgdata:
  mongodata: